config/routes.rb
Rails.application.routes.draw do
  get '/main', to: 'pages#main'
  get '/faq', to: 'pages#faq'
  get '/about', to: 'pages#about'
  resources :tasks do
    resources :orders
  end

  resources :comments

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }
  ActiveAdmin.routes(self)
  resources :categories do
    resources :tasks
  end

  resources :orders do
    member do
      post '/appoint', to: 'orders#appoint', as: 'appoint'
      get 'complete'
    end
  end

  resources :categories do
    member do
      get 'show_tasks'
    end
  end
  resources :contacts

  resources :users do
    member do
      get 'profile'
    end
    patch :save_profile, on: :collection
  end

  resources :reviews
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates_presence_of :body
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :task, optional: true
  belongs_to :comment, optional: true

  enum status: %i[active in_progress done]
  include EnumTranslatable
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates_uniqueness_of :user_id, scope: :task_id
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  has_many_attached :file
  has_many_attached :additional_file
  has_many :comments
  has_many :reviews

  validates :price, numericality: { greater_than: 0 }
  validates_presence_of :title, :description, :price, :deadline

  def rating
    quantity = if reviews.count == 0
                 1
               else
                 reviews.count
               end
    reviews.sum(&:rating) / quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: %i[customer contractor]
  include EnumTranslatable

  has_one_attached :avatar
  has_many :comments
  has_many :reviews
  validates :role, :first_name, :last_name, presence: true

  def avatar_thumbnail
    if avatar.attached?
      avatar.variant(resize: '150x150!').processed
    else
      'ava.png'
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.role = 'customer'
      user.first_name = 'Unknown'
      user.last_name = 'User'
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[destroy]
  def new
    @comment = Comment.new(user_id: params[:user_id], task_id: params[:task_id])
  end

  def create
    @comment = Comment.create(comment_params)
    if @comment.save
      redirect_to task_path(@comment.task)
    else
      flash.now[:error] = @comment.errors.messages
      render 'new'
    end
  end

  def show
    @active_order = Order.where(task_id: @task, status: 0)
  end

  def edit; end

  def update
    if @comment.update(comment_params)
      flash[:success] = 'Comment successfully updated!'
    else
      flash[:danger] = 'Something wrong, sorry!'
    end
    redirect_to @comment.task
  end

  def destroy
    @comment.destroy
    redirect_to @comment.task
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:user_id, :task_id, :body)
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  helper_method :appoint_order

  def show
    @order = Order.find(params[:id])
  end

  def appoint
    Order.where(task_id: params[:task_id]).update(implementer_id: params[:implementer_id], status: 1)
    redirect_to root_path
  end

  def complete
    Order.where(task_id: params[:task_id]).update(status: 2)
    redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:user_id, :task_id, :body, :implementer_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    render :main if current_user.nil?
  end

  def main; end
end

app/controllers/tasks_controller.rb
class TasksController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :get_children_list
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params.merge(author_id: current_user.id))
    @task.category = Category.find(params[:task][:category_id])
    if @task.save
      @active_order = Order.create(client_id: current_user.id, status: 0, task_id: @task.id)
      redirect_to @task
      flash[:success] = 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:success] = 'Comment successfully updated!'
    else
      flash[:danger] = 'Something wrong, sorry!'
    end
    redirect_to @task
  end

  def show
    @task = Task.find(params[:id])
    @comment = @task.comments
    @review = @task.reviews
    @test_category = Category.roots.ids[0]
    
    @try_task = Category.children_of(Category.roots.ids[0]).include?(@task.category)
  
    @order_task = Order.where(task_id: @task.id)
    @free_order = Order.where(task_id: @task.id, status: 0)
    @completed_order = Order.where(task_id: @task, client_id: current_user, status: 'done')

    @unpermitted = if @free_order.present? && !Order.where(implementer_id: current_user, status: 1).present?
                     true
                   else
                     false
                   end

    @allow_upload = if Order.where(task_id: @task, implementer_id: current_user).present? && !@task.file.present?
                      true
                    else
                      false
                    end
  end

  private

  def get_children_list
    @subcategories = Category.children_of(Category.roots.ids[0]) + Category.children_of(Category.roots.ids[1])
  end

  def task_params
    params.require(:task).permit(:title, :category_id, :category, :description, :price, :deadline, file: [],
                                 additional_file: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  after_action :rating
  def index
    @user = User.all
  end

  def save_profile
    @user.update(user_params)
    redirect_to root_path
  end

  def rating
    arr = Order.where(implementer_id: @user, status: 'done').ids # отримуєм масив з айді виконаних замовлень юзера
    marks = []
    arr.each do |id| # в циклі перевіряємо завдання, які було оцінено, і вносимо оцінку до масивy marks
      mark = Task.find(Order.find(id).task.id).rating
      marks << mark if mark > 0
    end
    @user.rating = if marks.empty?
                     0
                   else
                     marks.sum / marks.size
                   end
    @user.update(rating: @user.rating)
  end

  private

  def set_user
    @user = User.find(params[:id])
    @orderlist = Order.where(client_id: @user.id).or(Order.where(implementer_id: @user.id))
  end

  def user_params
    params.require(:user).permit(:email, :avatar, :first_name, :last_name, :description, :birthday, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment_show.html.erb
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
<h2 style="text-align: center;">Пропозиції</h2>
<div class="comment">
  <% @task.comments.each do |comment| %>
  <div class="col-lg-10">
    <div class="card shadow mb-5">
      <div class="card-header">
      	<h6><%=link_to comment.user.email, profile_user_path(comment.user_id)  %> <%=comment.user.rating%> </h6>
      </div>
      <div class="card-body">
        <p class="card-text"><%= comment.body %></p>
        <div style="text-align: center;">
           <% if current_user.role == "customer" and current_user.id == @task.author_id %>
           <% if @free_order.present? %>
           <%= button_to 'Прийняти', appoint_order_path(task_id: @task.id, implementer_id: comment.user_id), method: :post, class: "btn btn-success" %>
           <% else %>
           <i class="fa fa-times" aria-hidden="true">Не доступно</i>
           <%end %>
           <% end %>
	        	<% if current_user.email == comment.user.email %>
	            	<%= link_to (fa_icon "trash-o"), comment_path(comment), method: :delete, class: "btn btn-outline-dark",
	                              data: {confirm: 'Confirm delete your comment?'} %>
	             <% end %>
         </div>
      </div>

        <div class="row">

        </div>
    </div>
  </div>
<% end %>

  </div>

app/views/comments/new.html.erb
<div class="container pt-5">
<div class= "pt-5">
  <h3>  Чому саме ти повинен отримати це завдання? </h3>
  <div class="card shadow">
            <div class="card-body" style="background: #cccccc;">
<%= form_for @comment do |f| %>
<% if @comment.errors.any? %>
      <% @comment.errors.full_messages.each do |message| %>
      <h4 class="alert-danger"> <%= message %> </h4>
      <% end %>
    <% end %>
<div class="pt-5">

  <%= f.text_area :body, class: 'form-control', rows: "2" %>
</div>
<br>

<%= f.hidden_field :user_id %>
<%= f.hidden_field :task_id %>
<div><%= f.submit 'Опублікувати', :class => 'btn btn-success' %></div>
<% end %>
</div>
</div>
</div>
</div>