config/routes.rb
Rails.application.routes.draw do
  get '/main', to: 'pages#main'
  get '/faq', to: 'pages#faq'
  get '/about', to: 'pages#about'
  resources :tasks do
    resources :orders
  end

  resources :comments

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }
  ActiveAdmin.routes(self)
  resources :categories do
    resources :tasks
  end

  resources :orders do
    member do
      post '/appoint', to: 'orders#appoint', as: 'appoint'
      get 'complete'
    end
  end

  resources :categories do
    member do
      get 'show_tasks'
    end
  end
  resources :contacts

  resources :users do
    member do
      get 'profile'
    end
    patch :save_profile, on: :collection
  end

  resources :reviews
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates_presence_of :body
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :task, optional: true
  belongs_to :comment, optional: true

  enum status: %i[active in_progress done]
  include EnumTranslatable
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates_uniqueness_of :user_id, scope: :task_id
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  has_many_attached :file
  has_many_attached :additional_file
  has_many :comments
  has_many :reviews

  validates :price, numericality: { greater_than: 0 }
  validates_presence_of :title, :description, :price, :deadline

  def rating
    quantity = if reviews.count == 0
                 1
               else
                 reviews.count
               end
    reviews.sum(&:rating) / quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: %i[customer contractor]
  include EnumTranslatable

  has_one_attached :avatar
  has_many :comments
  has_many :reviews
  validates :role, :first_name, :last_name, presence: true

  def avatar_thumbnail
    if avatar.attached?
      avatar.variant(resize: '150x150!').processed
    else
      'ava.png'
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.role = 'customer'
      user.first_name = 'Unknown'
      user.last_name = 'User'
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  helper_method :appoint_order

  def show
    @order = Order.find(params[:id])
  end

  def appoint
    Order.where(task_id: params[:task_id]).update(implementer_id: params[:implementer_id], status: 1)
    redirect_to root_path
  end

  def complete
    Order.where(task_id: params[:task_id]).update(status: 2)
    redirect_to root_path
  end

  private

  def order_params
    params.require(:order).permit(:user_id, :task_id, :body, :implementer_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    render :main if current_user.nil?
  end

  def main; end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new(user_id: params[:user_id], task_id: params[:task_id])
  end

  def create
    @review = Review.create(review_params)
    if @review.save
      redirect_to root_path
    else
      flash.now[:error] = @review.errors.messages
      render 'new'
    end
  end

  def edit; end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:success] = 'Review successfully updated!'
    else
      flash[:danger] = 'Something wrong, sorry!'
    end
    redirect_to @review.task
  end

  def destroy
    @review.destroy
    redirect_to @review.task
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:user_id, :task_id, :rating)
  end
end

app/controllers/tasks_controller.rb
class TasksController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :get_children_list
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params.merge(author_id: current_user.id))
    @task.category = Category.find(params[:task][:category_id])
    if @task.save
      @active_order = Order.create(client_id: current_user.id, status: 0, task_id: @task.id)
      redirect_to @task
      flash[:success] = 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:success] = 'Comment successfully updated!'
    else
      flash[:danger] = 'Something wrong, sorry!'
    end
    redirect_to @task
  end

  def show
    @task = Task.find(params[:id])
    @comment = @task.comments
    @review = @task.reviews
    @test_category = Category.roots.ids[0]
    
    @try_task = Category.children_of(Category.roots.ids[0]).include?(@task.category)
  
    @order_task = Order.where(task_id: @task.id)
    @free_order = Order.where(task_id: @task.id, status: 0)
    @completed_order = Order.where(task_id: @task, client_id: current_user, status: 'done')

    @unpermitted = if @free_order.present? && !Order.where(implementer_id: current_user, status: 1).present?
                     true
                   else
                     false
                   end

    @allow_upload = if Order.where(task_id: @task, implementer_id: current_user).present? && !@task.file.present?
                      true
                    else
                      false
                    end
  end

  private

  def get_children_list
    @subcategories = Category.children_of(Category.roots.ids[0]) + Category.children_of(Category.roots.ids[1])
  end

  def task_params
    params.require(:task).permit(:title, :category_id, :category, :description, :price, :deadline, file: [],
                                 additional_file: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user
  after_action :rating
  def index
    @user = User.all
  end

  def save_profile
    @user.update(user_params)
    redirect_to root_path
  end

  def rating
    arr = Order.where(implementer_id: @user, status: 'done').ids # отримуєм масив з айді виконаних замовлень юзера
    marks = []
    arr.each do |id| # в циклі перевіряємо завдання, які було оцінено, і вносимо оцінку до масивy marks
      mark = Task.find(Order.find(id).task.id).rating
      marks << mark if mark > 0
    end
    @user.rating = if marks.empty?
                     0
                   else
                     marks.sum / marks.size
                   end
    @user.update(rating: @user.rating)
  end

  private

  def set_user
    @user = User.find(params[:id])
    @orderlist = Order.where(client_id: @user.id).or(Order.where(implementer_id: @user.id))
  end

  def user_params
    params.require(:user).permit(:email, :avatar, :first_name, :last_name, :description, :birthday, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/orders/_form.html.erb
<div class="pt-5" style="position: relative; top: 40px; left: 50px;">
  <h2> Rate this product and give your feedback </h2>
<%= form_with(model: @order) do |f| %>
    <% if @order.errors.any? %>
      <% @order.errors.full_messages.each do |message| %>
      <h4 class="alert-danger"> <%= message %> </h4>
      <% end %>
    <% end %>
  <div>
    <%= f.label :task_id %>
    <%= f.text_area :task_id, class: 'form-control', rows: "2" %>
  </div>
  <br>
  <%= f.hidden_field :task_id %>
  <div><%= f.submit %></div>
<% end %>
</div>

app/views/orders/edit.html.erb
<div class="form-wrap product-description-details mt-4">
  <h3 class="text-center"> Edit</h3>
  <%= render 'form'%>
</div> 

app/views/orders/show.html.erb
<div class="pt-5">
<h1><%= @order.task.id %></h1>
<%= link_to "Edit", edit_order_path(@order) %>
</div>

app/views/tasks/_attach.html.erb
<div class="container" style="width: 80%;">
  <div class="pt-5" style="text-align: center;">
    <h1 style="font-size: 400%;"> Вітаємо з виконанням завдання </h1>
      <div class="card shadow mb-3">
  <div class="card-body" style="background: #cccccc;">
  <%= form_with(model: task) do |form| %>
    <% if task.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

        <ul>
          <% task.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <div class="field">
      <%= form.label :file %><br/>
      <%= form.file_field :file, multiple: true,:style => 'font size: 100%;color: green;width:40%;background:white;border-radius: 8px;'%>
    </div>
  </br>
  </br>


    <div class="actions">
      <%= form.submit "Завантажити відповідь", :class =>'btn btn-success'%>
    </div>
  <% end %>
  </div>
</div>
</div>
</div>

app/views/tasks/_form.html.erb
<div class="pt-5" style="text-align: left;">
  
  <h1 style="color: black;"><strong>Оформлення замовлення</strong></h1>
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Предмет" %>: <nobr class="req">*</nobr></br>
    <%= form.select :category_id, options_from_collection_for_select(@subcategories, :id, :title)%>
  </div>
 
  <div class="field">
   <p>Назва роботи: <nobr class="req">*</nobr></p>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <p>Опис: <nobr class="req">*</nobr></p>
    <%= form.text_area :description, class: 'form-control', rows: "3" %>
  </div>
  <br>



  <div class="col-2">
  <div class="field">
    <p>Ціна: <nobr class="req">*</nobr></p>
    <%= form.text_field :price, class: 'form-control', placeholder: "вкажіть ціну в грн" %></br></br>
  </div>
  <div class="field">
    <p>Виконати до: <nobr class="req">*</nobr></p>
    <%= form.date_field :deadline %>
  </div>
  <br>
        <div class="field">
    <p>Вкласти файл: </p> 
    <%= form.file_field :additional_file, multiple: true %>
  </div>
</br>
  <div class="actions">
      <%= form.submit "Відправити",class: 'btn btn-success' %></br></br>
    </div>
</div>
<% end %>
</div>
<div style="height: 52px;">
</div> 

app/views/tasks/edit.html.erb
<div class="container" style="text-align: center;">
<h1>Editing Task</h1>

<%= render 'attach', task: @task %>

</br>
</br>

<%= link_to 'Повернутися до завдання', tasks_path , :class =>'btn btn-success'%>
</div>

app/views/tasks/index.html.erb
<script type="text/javascript">

setTimeout('window.history.back()',0);

</script>

app/views/tasks/new.html.erb
<div class="container">
	<div class="card shadow mb-3">
	<div class="card-body" style="background: #cccccc;">
<%= render 'form', task: @task %></div>

</div>
</div>

app/views/tasks/show.html.erb
<div class="container">
<div class="card shadow mb-3">

  <div class="card-body" style="background: #cccccc;">
		<p id="notice"><%= notice %></p>
		<p class="pt-5">
		<h1><%= @task.title %></h1>
			 <h5><%= @task.category.parent.title %> / <%= @task.category.title %></h5>
			<h6> Замовник: <%=link_to User.find(@task.author_id).email, profile_user_path(@task.author_id) , :style => 'text-decoration: none; color: #188753; font-weight: bold;'%></h6>
		</p>
		</p>

		<p>
		  <strong>Опис:</strong>
		  <%= @task.description %>
		</p>
		 
		<p>
		  <strong>Ціна:</strong>
		  <%= @task.price %>
		</p>
		<p>
		  <strong>Виконати до:</strong>
		  <%= @task.deadline %>
		</p>

		<% if @try_task and current_user.role == 'contractor'%>
		<%= link_to 'Виконати тестове завдання', appoint_order_path(task_id: @task.id, implementer_id: current_user), method: :post, class: "btn btn-success"%>
		<% end %>

		<% if @task.additional_file.present? %>
		<p>
		  <strong>Вкладені файли:</strong>
		  <% @task.additional_file.each do |additional_file|%>
		<%= link_to 'Завантажити' , rails_blob_path(additional_file, only_path: true),download: '' %>
		<%end%>
		</p>
		<% end %>
		 <% if @unpermitted and current_user.role == 'contractor'%>

		<% if !@try_task and current_user.role == 'contractor'%>
		<div><%= link_to 'Відправити пропозицію', new_comment_path(user_id: current_user, task_id: @task), method: :get, class: 'btn btn-success' %></div>
		<% end %>
			
		<% end %>
		<% if @allow_upload %>

		<%= link_to 'Завантажити відповідь', edit_task_path(@task), :class => 'btn btn-success', :style =>'text=text-decoration: none;'%>
		<br>
		<% end %>
		<% if current_user.id == @task.author_id and @completed_order.present? %>
		<div><%= link_to 'Оцінити виконання', new_review_path(user_id: current_user, task_id: @task, method: :get), :class => "btn btn-success"%></div>

		<% end %>
	</div>
</div>
 <div class="col-lg-6 sm-12">
   <%= render 'comments/comment_show' %>
   </div>
</div>

app/views/users/profile.html.erb
<div class="container">
  <div class="pt-5">
  <br>
    <div class="row">
      <div class="col-2 pt-1">
        <%= image_tag(@user.avatar_thumbnail, {:class => "round"})%>
      </div>
      <div class="col-4 pt-1">
        <h1><%= @user.first_name %> <%= @user.last_name %></h1>
        <p><%= @user.description %></p>
          <% @user.rating.to_i.times do %>
          <i class="fa fa-star" style="color: #ffde00"></i>
        <% end %>
      </div>
    </div>
  </div>
  
  
<div class="row">
  <div class="pt-3">
    <div class="col-4 pt-1">
  <% if @user == current_user %>
  <div class="d-flex justify-content-left"><%= link_to "Редагувати профіль", edit_user_registration_path, class: "btn btn-success" %></div>
  <% end %>
</div>
</div>
</div>

<hr>
<h4 class="d-flex justify-content-center"> Мої роботи </h4>

<table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Номер замовлення</th>
      <th scope="col">Назва роботи</th>
      <th scope="col">Виконавець</th>
      <th scope="col">Замовник</th>
      
      <th scope="col">Статус</th>
      <th scope="col">Результат</th>
      <th scope="col">Підтвердити</th>
      <th ></th>
    </tr>
  </thead>

  <tbody>

  <% @orderlist.each do |order| %>
    <tr>
      <td><%= order.task_id %></td>
      <td><%= link_to order.task.title, task_path(order.task)%></td>
            <% if order.status == "in_progress" or order.status == "done"%>
      <td><%= link_to User.find(order.implementer_id).email , profile_user_path(order.implementer_id), class: 'nav-link'%></td>
      <%else%>
      <td>Це завдання ще ніхто не виконує</td>
      <% end %>
      <td><%= link_to User.find(order.client_id).email , profile_user_path(order.client_id), class: 'nav-link'%></td>

      <td><%= order.status_ua %></td>
      <% if order.task.file.present? %>
        <td><% order.task.file.each do |file|%>
          <%= link_to 'Завантажити' , rails_blob_path(file, only_path: true),download: '' %>
        <%end%></td>
          <% else %>
          <td><p><%= link_to 'Show task', task_path(order.task) %></p></td>
      <% end %>

      <% if order.client_id == current_user.id %>
      <% if order.status == 'in_progress' %>
      <td><h5>Завдання виконується </h5></td>
      <% if order.task.file.present? %>
     <td><%= link_to "Підтвердити виконання", complete_order_path(task_id: order.task.id), class: 'btn btn-success' %></td>
     <%end%>
        <% elsif order.status == 'done' and order.client_id == current_user.id %>
        <td><h5>Завдання виконано </h5></td>
        <% else %>
            <td><h5>Завдання поки що ніхто не виконує</h5></td>
            <%end%>
      <%else%>
      <%if order.status == 'in_progress'%>
      <td><h5>Завдання виконується </h5></td>
      <%else%>
      <td><h5>Завдання виконано </h5></td>
      <%end%>
      <%end%>
      </tr>
    <% end %>
  </tbody>
</table>
</div>