config/routes.rb
Rails.application.routes.draw do
  get '/main', to: 'pages#main'
  get '/faq', to: 'pages#faq'
  get '/about', to: 'pages#about'
  resources :tasks do
    resources :orders
  end

  resources :comments

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth' }
  ActiveAdmin.routes(self)
  resources :categories do
    resources :tasks
  end

  resources :orders do
    member do
      post '/appoint', to: 'orders#appoint', as: 'appoint'
      get 'complete'
    end
  end

  resources :categories do
    member do
      get 'show_tasks'
    end
  end
  resources :contacts

  resources :users do
    member do
      get 'profile'
    end
    patch :save_profile, on: :collection
  end

  resources :reviews
  root 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :tasks
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates_presence_of :body
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :task, optional: true
  belongs_to :comment, optional: true

  enum status: %i[active in_progress done]
  include EnumTranslatable
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :task

  validates_uniqueness_of :user_id, scope: :task_id
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
  has_many_attached :file
  has_many_attached :additional_file
  has_many :comments
  has_many :reviews

  validates :price, numericality: { greater_than: 0 }
  validates_presence_of :title, :description, :price, :deadline

  def rating
    quantity = if reviews.count == 0
                 1
               else
                 reviews.count
               end
    reviews.sum(&:rating) / quantity
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: %i[customer contractor]
  include EnumTranslatable

  has_one_attached :avatar
  has_many :comments
  has_many :reviews
  validates :role, :first_name, :last_name, presence: true

  def avatar_thumbnail
    if avatar.attached?
      avatar.variant(resize: '150x150!').processed
    else
      'ava.png'
    end
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[google_oauth2]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.role = 'customer'
      user.first_name = 'Unknown'
      user.last_name = 'User'
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    render :main if current_user.nil?
  end

  def main; end
end

app/controllers/tasks_controller.rb
class TasksController < InheritedResources::Base
  before_action :authenticate_user!
  before_action :get_children_list
  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params.merge(author_id: current_user.id))
    @task.category = Category.find(params[:task][:category_id])
    if @task.save
      @active_order = Order.create(client_id: current_user.id, status: 0, task_id: @task.id)
      redirect_to @task
      flash[:success] = 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      flash[:success] = 'Comment successfully updated!'
    else
      flash[:danger] = 'Something wrong, sorry!'
    end
    redirect_to @task
  end

  def show
    @task = Task.find(params[:id])
    @comment = @task.comments
    @review = @task.reviews
    @test_category = Category.roots.ids[0]
    
    @try_task = Category.children_of(Category.roots.ids[0]).include?(@task.category)
  
    @order_task = Order.where(task_id: @task.id)
    @free_order = Order.where(task_id: @task.id, status: 0)
    @completed_order = Order.where(task_id: @task, client_id: current_user, status: 'done')

    @unpermitted = if @free_order.present? && !Order.where(implementer_id: current_user, status: 1).present?
                     true
                   else
                     false
                   end

    @allow_upload = if Order.where(task_id: @task, implementer_id: current_user).present? && !@task.file.present?
                      true
                    else
                      false
                    end
  end

  private

  def get_children_list
    @subcategories = Category.children_of(Category.roots.ids[0]) + Category.children_of(Category.roots.ids[1])
  end

  def task_params
    params.require(:task).permit(:title, :category_id, :category, :description, :price, :deadline, file: [],
                                 additional_file: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyHub</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
 <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application' %>

  </head>

<body>
<div id="wrapper">
<div id="header">
    <header>
      <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top">
            <div class="container-fluid">
              <a class="navbar-brand" href="/"><strong><span style="color: #000000;">Study</span><span style="color: #018c4b;">Hub</span></strong></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

              <div class="collapse navbar-collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                  <li class="nav-item active">
                    <a class="nav-link" aria-current="page" href="/about"><strong>Про нас</strong></a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" aria-current="page" href="/faq"><strong>FAQ</strong></a>
                  </li>
                  <% if current_user %>
                                  <% if current_user.role == 'customer' %>
                                  
                    <strong><%= link_to 'Створити завдання', new_task_path, class: 'nav-link active'%></strong>
                
                    <% end %>
                    <% end %>
                </ul>
              </div>
                        <% if current_user %>
                        <%= link_to current_user.email, profile_user_path(current_user), class: 'btn btn-success btn-sm'%>&emsp;
                    <%= link_to 'Вихід', destroy_user_session_path, method: :delete, class: 'btn btn-outline-success text-end btn-sm'%>
                  <% else %>
                  <div style="right: 1000px;">
                   <%= link_to 'Вхід',new_user_session_path,class: 'btn btn-success btn-sm'%>
                  <% end %>
            </div>
          </nav>
    </header>
</div>
<div id="content">



    <!--<div class="container pt-5">
      <div class="row pt-5">
      
      <div class="col-3 pt-3">
  <div class="card bg-light h-1">
    <div class="card-body text-center">
      
    </div>
  </div>
  </div>
  
</div>
</div>-->


    <%= yield %>




</div>
<div id="footer">
      <div class="footer">

    <footer class="bg-dark  text-white">
      <!-- Grid container --> 

      <div class="container p-4 pb-0">
        <!-- Section: Social media -->
         

        <section class="mb-2">
          <!-- Facebook -->
          <div class="row">
            <div class="col-4">
            <a class="navbar-brand" href="/"><strong><span style="color: #FFFFFF;">Study</span><span style="color: #018c4b;">Hub</span></strong></a></br>
            <%= link_to "Зворотній зв'язок", new_contact_path, class: "btn btn-outline-light btn-floating m-1", style: "text-align: left;"%>  
            </div>

            <div class="col-4 text-center p-4">
            <a class="btn btn-outline-light  btn-floating m-1" href="https://www.facebook.com/" role="button"
              ><i class="fab fa-facebook-f"></i
            ></a>

            <!-- Twitter -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://twitter.com/" role="button"
              ><i class="fab fa-twitter"></i
            ></a>

            <!-- Google -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://google.com/" role="button"
              ><i class="fab fa-google"></i
            ></a>

            <!-- Instagram -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://instagram.com/" role="button"
              ><i class="fab fa-instagram"></i
            ></a>

            <!-- Linkedin -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.linkedin.com/" role="button"
              ><i class="fab fa-linkedin-in"></i
            ></a>

            <!-- Github -->
            <a class="btn btn-outline-light btn-floating m-1" href="https://www.github.com/" role="button"
              ><i class="fab fa-github"></i
            ></a>
          </div>
          <div class="col-4 p-3" style="text-align: right;">
            <i class="fab fa-cc-paypal" style="font-size: 70px;"></i>&emsp;
           <i class="fab fa-cc-visa" style="font-size: 70px;"></i>


          </div>

          </div>
        </section>
        <!-- Section: Social media -->
      </div>
      <!-- Grid container -->

      <!-- Copyright -->
      <div class="text-center">
        StudyHub © 2021
      </div>
      <!-- Copyright -->
    </footer>

</div>
</div>
</body>


</html>

app/views/pages/about.html.erb
<%= stylesheet_link_tag 'about' %>
 <%= image_tag("Frame2.png", :class =>'image')%>
<div class="position">
<div class="row">
  
    <div class="col-6" style="text-align: center;">
      <h1><strong><span style="color: #000000;font-size: 150px;">Study</span><span style="color: #018c4b;font-size: 150px;">Hub</span></strong></h1>
</br> <strong><span style="color: #000000; font-size: 80px">Трохи більше про нас :)</span></strong></br></br>
</div>
</div>
</div>
<div style="background: #fffee8; text-align: center; font-size: 20pt;">
      <p><strong></br><span style="color: #000000;">Study</span><span style="color: #018c4b;">Hub</span></strong>
      <span> - це студентський фріланс-сервіс, де можна замовити роботу будь-якої складності - від простого і недорогого реферату до дисертації. Теми - будь-які. Предмети - все, що викладаються в коледжах і вузах. Такe охоплення забезпечує багатотисячний обсяг авторів, серед яких:</span></br></br></p>
</div>


<div class="row">
  <div class="col-4" style="">
  </div>
    <div class="col-4" style="">
      <div style="font-size: 22px;">
      <p><strong><span style="color: #018c4b;">&#10004;</span>викладачі вузів</br>
      <span style="color: #018c4b;">&#10004;</span>аспіранти</br>
      <span style="color: #018c4b;">&#10004;</span>Переможці українських та міжнародних олімпіад</br>
      <span style="color: #018c4b;">&#10004;</span>Представники різних наукових професій</br>
      <span style="color: #018c4b;">&#10004;</span>Інженери, картографи, архітектори</br>
      <span style="color: #018c4b;">&#10004;</span>Перекладачі і поліглоти</br>
      <span style="color: #018c4b;">&#10004;</span>Студенти, які добре знаються на предметі</strong></p>
</div>
</div>
</div>

<div style="background: #fffee8; text-align: center; font-size: 20pt;">
      <p><strong></br><span style="color: #000000;">Study</span><span style="color: #018c4b;">Hub</span></strong>
      <span>- це сервіс для укладення безпечних угод між замовниками та авторами навчальних робіт. Ми не є посередниками, ми лише надаємо:</span></br></br></p>
</div>

<div class="row">
  <div class="col-4" style="">
  </div>
    <div class="col-4" style="">
      <div style="font-size: 22px;">
      <p><strong><span style="color: #018c4b;">&#10004;</span>майданчик для зустрічей;</br>
       <span style="color: #018c4b;">&#10004;</span>зручний функціонал для публікації замовлень і відбору виконавців;</br>
       <span style="color: #018c4b;">&#10004;</span>справедливий арбітраж в спірних випадках;</br>
       <span style="color: #018c4b;">&#10004;</span>взаємні гарантії безпеки оплати.</br></strong></p>
      </div>
    </div>
</div>
<div style="background: #fffee8; text-align: center; font-size: 40pt;">
      <span><strong>Наші гарантії</span></strong></p>
      <p style="font-size: 20pt;">Вибираючи виконавця, ви бачите його рейтинг в системі. Наші автори зацікавлені в якісному і своєчасному виконанні кожного завдання, так як ризикують своїм рейтингом і репутацією. У нас немає випадкових людей - все автори досвідчені виконавці і працюють на ринку студентських послуг довгий час.</p>
      <br>
</div>

app/views/pages/faq.html.erb
<%= stylesheet_link_tag 'faq' %>
<%= image_tag("Frame2.png", :class =>'image')%>

<div class="row">
      <div class="position">
        <div class="col-6" style="text-align: center; ">
        </br> <strong><p style="color: #000000; font-size: 100px"> Часті запитання?</p></strong> 
        <p style="font-size: 30px"><strong>Допомога в навчанні, проведення консультацій з кращими експертами,</br> копірайтинг і переклади</strong></p></br></br>
      </div>
  </div>
</div>

<div style="background: #fffee8; text-align: center; font-size: 24pt;">
      <span><strong>Як зареєструватись на StudyHub?</span></strong></p>
</div>
<div class="container">
  <p style="font-size: 20pt;">&emsp;Для роботи на сайті StudyHub вам необхідно зареєструватися. Процедура реєстрації є безкоштовною та ви можете обрати роль:</br>
-замовника</br>
-виконавця (автора робіт)</br>
&emsp;Ви можете зареєструвати тільки один акаунт замовника і один акаунт виконавця. У разі реєстрації більшої кількості облікових записів, все акаунти можуть бути заблоковані без попередження.
Щоб зареєструватись на сайті у відповідних полях вкажіть ім’я та прізвище, введіть email і пароль, оберіть тип акаунту (замовник/ виконавець).
</p>
</div>

<div style="background: #fffee8; text-align: center; font-size: 24pt;">
      <span><strong>Скільки коштують послуги сервісу?</span></strong></p>
</div>
<div class="container">
  <p style="font-size: 20pt;">&emsp;Завдяки роботі замовника з виконавцем безпосередньо, замовляти роботу на нашому сервісі набагато вигідніше, ніж в рефератних агентствах.</br>
&emsp;Замовник визначає терміни виконання роботи і її вартість, обирає виконавця серед безлічі пропозицій і працює з ним безпосередньо.</br> 
&emsp;Виконавець бере замовлення на виконання і заробляє гроші, співпрацює з тими замовниками, які йому подобаються і пише роботи на улюблені теми за вигідною ціною. Наш сервіс гарантує - правильно виконана робота в термін буде сплачена в повному обсязі.</br>
&emsp;Комісія, що стягується з замовника за використання ресурсу - 15%. 
</p>
</div>

<div style="background: #fffee8; text-align: center; font-size: 24pt;">
      <span><strong>Публічна оферта</br>
      Договір публічної оферти про надання інформаційно-консультаційних послуг</span></strong>
</div>
<div class="container">
  <p style="font-size: 20pt;">&emsp;Цей Договір – офіційна пропозиція компанії “StudyHub” (надалі – Виконавець) для будь-якої юридичної або фізичної особи (надалі – Замовник), яка приймає цю оферту на зазначених нижче умовах.</br>  
&emsp;Відповідно до пункту 2 статті 642 Цивільного кодексу України прийняттям оферти (акцепту) вважається вчинення дії відповідно до зазначених в публічній пропозиції умов договору, оскільки акцепт прирівнюється до укладення договору. Момент укладення даного Договору – момент зарахування коштів на рахунок виконавця від Замовника одним із запропонованих способів оплати.</br>
 
&emsp;Момент припинення дій Договору – повне виконання сторонами своїх зобов’язань або настання інших підстав, прописаних в Оферті. Відповідно до статей 633 і 641 Цивільного кодексу України цей Договір є публічним, має повноцінну юридичну силу і еквівалентний усній угоді.</br>
 
&emsp;&emsp;Визначення та терміни</br>
 
 Для цілей цієї Оферти наведені нижче терміни вживаються в такому значенні (якщо інше не мається на увазі контекстом):</br>
  
“Договір” – угоду між Замовником та Виконавцем на предмет надання інформаційно-консультаційних послуг, укладену шляхом акцепту оферти.</br>
 
“Замовлення” – послуга з пропонованого асортиментного переліку, необхідність надання якої вказана Замовником при оформленні заявки.</br> 
 
“Замовник” – фізична або юридична особа, яка прийняла цю Оферту.</br>
 
“Виконавець” – автори компанії “StudyHub”, в особі яких представлена ​​вся компанія.</br>
 
“Оферта” – справжній публічний договір-пропозиція послуги про компанію “StudyHub”.</br>
 
&emsp;&emsp;Предмет договору</br>
 
2.1. Виконавець пропонує інформаційні та консультаційні послуги, що є предметом Оферти. Основа надання – платна. Умови співпраці прописані цим Договором.</br>
 
2.2. Інформаційно-консультаційні послуги не можна вважати освітніми або іншими ліцензованими видами послуг. Це просвітницький, допоміжний матеріал, відповідальність за використання якого лежить на Замовнику.</br>
 
2.3. Термін, умови виконання, вартість, обсяг і межі послуг визначаються умовами конкретної угоди в індивідуальному порядку, з урахуванням побажань Замовника.</br>
 
2.4. Виконавець взаємодіє з Замовником через листування по електронній пошті. Таким способом направляються вихідні дані, важливі повідомлення, проміжні результати, повідомлення.</br>
 
2.5. Предмет Договору не може бути істотно змінений без узгодженого взаємного рішення сторін.</br>

    </p>
</div>

<div style="background: #188753; text-align: center; font-size: 30pt;">
      <span><strong>Замовнику</span></strong>
</div>
<div style="background: #fffee8; text-align: center; font-size: 24pt;">
      <span><strong>Як оформити замовлення?</span></strong>
</div>
<div class="container">
  <p style="font-size: 20pt;">&emsp;1. У профілі натисніть кнопку “Створити завдання” та заповніть форму “Оформлення замовлення”.</br>
                &emsp;2. Ваше завдання з’явиться в списку замовлень.</br>
                &emsp;3. Тепер чекайте привабливих пропозицій від виконавців.</br>

    </p>
</div>

<div style="background: #fffee8; text-align: center; font-size: 24pt;">
      <span><strong>Як вибрати виконавця і оплатити замовлення?</span></strong>
</div>
<div class="container">
  <p style="font-size: 20pt;">&emsp;Оберіть виконавця серед пропозицій на сторінці вашого замовлення, натиснувши ‘'Прийняти’’.</br>
                &emsp;Замовлення оплачується в розмірі 100%, але це зовсім не означає, що гроші переходять на рахунок виконавця і стають доступні. Ми резервуємо їх в системі і переведемо виконавцю тільки в тому випадку, якщо отримаємо від вас підтвердження, що робота виконана і відповідає початковим вимогам.

    </p>
</div>

<div style="background: #fffee8; text-align: center; font-size: 24pt;">
      <span><strong>Де знайти виконану роботу та що далі?</span></strong>
</div>
<div class="container">
  <p style="font-size: 20pt;">&emsp;Коли робота буде виконана, у профілі в “Мої замовлення” статус зміниться з “Виконується” на “Виконано” та ви можете завантажити роботу, натиснувши кнопку “Завантажити відповідь” (результат).</br>
  &emsp;Якщо ви впевнені, що робота виконана коректно і відповідає всім обумовленим вимогам, прийміть роботу відразу. Виконавець буде вам вдячний, адже він відразу зможе вивести зароблені кошти.</br>
  &emsp;Важливо оцінити роботу виконавця у формі, яка буде запропонована після завантаження виконаної роботи.
    </p>
</div>

<div style="background: #188753; text-align: center; font-size: 30pt;">
      <span><strong>Виконавцю</span></strong>
</div>

<div style="background: #fffee8; text-align: center; font-size: 24pt;">
      <span><strong>Як обрати замовлення?</span></strong>
</div>
<div class="container">
  <p style="font-size: 20pt;">&emsp;1. Вивчіть список замовлень.</br>
                &emsp;2.Виберіть цікаве вам замовлення і перейдіть на сторінку замовлення для детального ознайомлення із завданням. Особливо зверніть увагу на термін здачі роботи. Як правило, замовники уважно ставляться до заповнення цього поля при публікації замовлення і хочуть отримати виконану роботу не пізніше цієї дати.</br>
                &emsp;3.Якщо вас зацікавило конкретно замовлення і ви впевнені, що впораєтеся з його виконанням на відмінно, тоді саме час повідомити про це замовника. Для цього залиште пропозицію на сторінці замовлення.</br>
                &emsp;4.Після публікації ваша пропозиція з'явиться серед інших пропозицій виконавців.</br>
                &emsp;5.Якщо ваша пропозиція була обрана замовником, то в профілі в списку “Мої роботи” з'являються відповідні деталі. 

    </p>
</div>

<div style="background: #fffee8; text-align: center; font-size: 24pt;">
      <span><strong>Як формується рейтинг?</span></strong>
</div>
<div class="container">
  <p style="font-size: 20pt;">&emsp;Після завантаження виконаної роботі замовником, останній має оцінити задоволеність кінцевим результатом у спеціальній формі від 1-5 балів. Загальний рейтинг - це середнє арифметичне балів за всі замовлення.
</p>
  </div>

<div style="background: #fffee8; text-align: center; font-size: 24pt;">
      <span><strong>Коли замовлення оплачується?</span></strong>
</div>
<div class="container">
  <p style="font-size: 20pt;">&emsp;Замовлення оплачується в розмірі 100%, але це зовсім не означає, що гроші переходять на ваш рахунок і стають доступні. Ми резервуємо їх в системі і переведемо тільки в тому випадку, якщо отримаємо від замовника підтвердження, що робота виконана і відповідає початковим вимогам. У разі якщо замовник приймає роботу, кошти, заморожені сервісом за замовлення, відразу ж стануть доступні.
</p>
</div>

app/views/pages/home.html.erb
 <%= stylesheet_link_tag 'home' %>
 <div class="pt-5">
</div>
   <%= image_tag("Frame3.png", :class =>'image')%>


   <h1 style="color: black;">Обери свою категорію</h1>

  <h2>
    <div class="container pt-5">
    <div class="row">
    <% Category.roots.each do |category| %>

  <div class="col-6 pt-5 ">
    
      
        <p><%= link_to category.title, category_path(category), {:style=>'color:#FFFFFF; font-size: 40px; text-decoration:none;
          font-weight:bold; display: block;text-align: center;', :class => "btn btn-success"} %></p>
      
    
  </div>
  <% end %>
</div>
</h2>

app/views/pages/main.html.erb
<%= stylesheet_link_tag 'main' %>
<body>
<div id="wrapper">
  <div id="content">
    <div class="row">
      <div class="col-12 pt-5">    
        <h1><strong><span style="color: #000000;">Study</span><span style="color: #188753;">Hub</span></strong></h1>
        <h2></br> <strong><span style="color: #000000;"> Фріланс біржа для студентів та експертів.</span></strong></br></br> 
        Допомога в навчанні, проведення консультацій з кращими експертами,</br> копірайтинг і переклади</br></br>
        <button onclick="location.href='users/sign_in'" type="button" class="btn btn-outline-success btn-lg">Розмістити завдання</button>&emsp;&emsp;
        <button onclick="location.href='users/sign_in'" type="button" class="btn btn-outline-success btn-lg">Виконати завдання</button></h2>
      </div>

      <div class="col-12">
        <%= image_tag("Frame1.png", :class =>'image')%>
      </div>

      <div class="container">
        <div style="text-align: center; font-size: 20pt;">
                <strong>
                </br>
                <p>У нас можна розмістити або виконати різноманітні завдання</p>
                </strong>
        </div><
        
<div class="container">
        <div class="row">
          <div class="col-3 pt-1">
            <div class="card h-100">
              <button onclick="location.href='users/sign_in'" type="button" class="btn btn-outline-success btn-lg"><strong></br>Дипломна робота</br></br></strong></button></h2>
            </div>
          </div>
          <div class="col-3 pt-1">
            <div class="card h-100">
              <button onclick="location.href='users/sign_in'" type="button" class="btn btn-outline-success btn-lg"><strong></br>Курсова робота</br></br></strong></button></h2>
            </div>        
          </div>

          <div class="col-3 pt-1">
            <div class="card h-100">
              <button onclick="location.href='users/sign_in'" type="button" class="btn btn-outline-success btn-lg"><strong></br>Контрольна робота</br></br></strong></button></h2>
            </div>        
          </div>

          <div class="col-3 pt-1">
            <div class="card h-100">
              <button onclick="location.href='users/sign_in'" type="button" class="btn btn-outline-success btn-lg"><strong></br>Реферат</br></br></strong></button></h2>
            </div>
          </div>
        </div>
      </div>



        <div class="pt-5"></div>
        <head>
          <meta charset="utf-8">
          <title>Слой-ссылка</title>
          <style>
          </style>
        </head> 

        <body> 
          <div class="link">
           <a href="/users/sign_in"></a>
          </div>
        </body></div>

      <!--</div>
      </div>-->

        <div style="background: #a4efcb; text-align: center; font-size: 20pt;">
              <p><strong></br><span style="color: #000000;">Study</span><span style="color: #188753;">Hub</span>
              <span style="color: white;"> - найкращий спосіб отримати допомогу у навчанні</span></br></br></strong></p>
        </div>

        <div>

        <div class="container pt-5">
          <div class="row">
            <div class="col-2 pt-1">
              <p class="outline-success" style="text-align: center;"><strong><i class="fas fa-shield-alt" style="font-size: 90px"></i></strong></p>
            </div>
            <div class="col-6 pt-1">
              <p style="font-size: 17pt;"><strong>Безпечна угода</strong></p>
              <p>Виконавець отримує грошові кошти тільки після успішного завершення роботи</p>     
            </div>       
          </div>
        </div>
      <!--</div>
      </div>-->

      <div class="container pt-5">
        <div class="row">
          <div class="col-2 pt-1">
            <p class="outline-success" style="text-align: center;"><strong><i class="fas fa-users" style="font-size: 90px"></i></strong></p>
          </div>
          <div class="col-6 pt-1">
            <p style="font-size: 17pt;"><strong>Відповідальність</strong></p>
            <p>Оперативно вирішуємо питання і виправляємо непорозуміння</p>    
          </div>       
        </div>
      </div>
      <!--</div>
      </div>-->

      <div class="container pt-5">
        <div class="row">
          <div class="col-2 pt-1">
            <p class="outline-success" style="text-align: center;"><strong><i class="fas fa-medal" style="font-size: 90px"></i></strong></p>
          </div>
          <div class="col-6 pt-1">
            <p style="font-size: 17pt;"><strong>Висока якість послуг</strong></p>
            <p>Виконавці зацікавлені в якісному виконанні кожного завдання, так як ризикують своїм рейтингом та репутацією</p>   
          </div>       
        </div>
      </div>
      <!--</div>
      </div>--> 

      <div class="container pt-5">
        <div class="row">
          <div class="col-2 pt-1">
            <p class="outline-success" style="text-align: center;"><strong><i class="fas fa-user-secret" style="font-size: 90px"></i></strong></p>
          </div>
          <div class="col-6 pt-1">
            <p style="font-size: 17pt;"><strong>Конфіденційність</strong></p>
            <p>Не розголошуємо інформацію про клієнтів</p>
            <br> 
            <br> 
            <br>  
          </div>      
        </div>
      </div>
    </div>
  </div> 


</body>